import Footer from "@/components/footer";
import Header from "@/components/header";
import { Providers } from "@/components/providers"
import Sidebar from "@/components/sidebar";
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { getServerSession } from "next-auth";;
import { Roboto } from 'next/font/google';
import { redirect } from "next/navigation";


const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700', '900'],
  variable: '--font-roboto',
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: React.ReactNode
}

export default async function RootLayout({ children }: LayoutProps) {
  const session = await getServerSession();

  if (!session) {
    redirect('/login');
  }

  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Providers>
          <main className="flex min-h-screen flex-row bg-white">
            <Sidebar />
            <div className="-ml-[280px] flex flex-grow flex-col transition-all duration-150 ease-in md:ml-0">
              <Header />
              <div className="flex h-full items-start justify-start bg-gray-light">
                {children}
              </div>
              <Footer />
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
